[package]
name = "wfc-rails"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
rand = "0.8.5"
rust-embed = { version = "8.4.0", features = ["include-exclude"] }

[build-dependencies]
winres = "0.1.12"
